### ISSUE TITLE
[inappmessaging] From Firebase Crashlytics: Crash occurs in io.karte.android.inappmessaging.internal.view#WebView.kt: 121

### ISSUE THREAD

**Issue by myamamic** [plaidev/karte-android-sdk#21]
## Expected Behavior

Does not crash.

## Current Behavior

Our application rarely crash.

## Possible Solution

N/A

## Steps to Reproduce

Sorry, we still can't reproduce this issue.  It just occurs on several customers.

## SDK Version

- core 2.22.0
- inappmessaging 2.16.1
- notifications 2.10.0
- variables 2.4.0
- visualtracking N/A
- inbox N/A
- Karte Gradle Plugin N/A

## Android Version

Crashlytics report says it occurs on below devices.

- Android 12
- Android 13

## Build Environment

- Android Studio Version 2022.3.1
- Gradle Version 8.1.1
- Android Gradle Plugin Version 8.1.0

## Context Details

We got some crash reports in Firebase Crashlytics, the reports show the issue occurs in io.karte.android.inappmessaging.internal.view#WindowView.kt:121 . 

Is that a issue in the KARTE library? or we'd like to know how to avoid the crash.
```
Fatal Exception: java.lang.IllegalArgumentException: View=xe.e{25c66ff V.E...... ......I. 0,0-0,0 #7f0a0155 app:id/karte_overlay_view} not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:541)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:445)
       at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:201)
       at io.karte.android.inappmessaging.internal.view.WindowView$show$1.run(WindowView.kt:123)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7918)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

## Logs

N/A

## Possible Implementation

- We don't publish any popup action from KARTE console when the application crashed.
- Our application uses KARTE variables to get variable settings.

**Comment by myamamic** [comment]
Last month, We updated to the latest karte sdks.
Since updating to the following versions, this issue has not occurred. Thanks 🎉 

- core 2.21.2 -> 2.25.0
- inappmessaging 2.15.0 -> 2.19.1
- notifications 2.9.1 -> 2.11.0
- variables 2.4.0 -> 2.7.0
- visualtracking N/A
- inbox N/A
- Karte Gradle Plugin N/A
