### ISSUE TITLE
WindowManager$BadTokenException - Unable to add window -- token null is not valid; is your activity running?

### ISSUE THREAD

**Issue by sontnfabbi** [plaidev/karte-android-sdk#24]
## Expected Behavior
the crash was reported in firebase

## SDK Version
    implementation 'io.karte.android:core:2.22.0'
    implementation 'io.karte.android:inappmessaging:2.18.0'  //アプリ内メッセージ機能を提供します。
    implementation 'io.karte.android:notifications:2.10.0'  //プッシュ通知の受信および効果測定機能を提供します。
    implementation 'io.karte.android:visualtracking:2.9.0'

## Android Version
All version 

## Build Environment

- Android Studio Version Android Studio Jellyfish | 2023.3.1
- Gradle Version 8.2.2
- Android Gradle Plugin Version x.x.x

## Logs

Log from firebase crashlytics
`
      Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:1261)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:431)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:110)
       at io.karte.android.inappmessaging.internal.view.WindowView.showInternal(WindowView.kt:153)
       at io.karte.android.inappmessaging.internal.view.WindowView.access$getWindowManager$p(WindowView.kt:65)
       at io.karte.android.inappmessaging.internal.view.WindowView.access$showInternal(WindowView.kt:65)
       at io.karte.android.inappmessaging.internal.view.WindowView$show$1.run(WindowView.kt:120)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:271)
       at android.app.ActivityThread.main(ActivityThread.java:8305)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
    
`

**Comment by TakayukiCho** [comment]
This bug is fixed on the newly updated library, InAppMessaging 2.19.1.

For further information, please take a look at [our release note](https://github.com/plaidev/karte-android-sdk/blob/master/CHANGELOG.md#releases---20240603).

**Comment by sontnfabbi** [comment]
ありがとうございました。

> This bug is fixed on the newly updated library, InAppMessaging 2.19.1.
> 
> For further information, please take a look at [our release note](https://github.com/plaidev/karte-android-sdk/blob/master/CHANGELOG.md#releases---20240603).
